export type Post = {
  aisummary: string;
  author: string;
  authoruuid: string;
  content: string;
  coverimagefile: file | null;
  coverimagelink: string;
  coverimagelinkavif: string;
  coverimagelinkwebp: string;
  coverimagelinkpng: string;
  coverimagelink100x300avif: string;
  coverimagelink100x300webp: string;
  coverimagelink100x300png: string;
  coverimagelink200x600avif: string;
  coverimagelink200x600webp: string;
  coverimagelink200x600png: string;
  coverimagealt: string;
  date: string;
  mintoread: number;
  slug: string;
  subtitle: string;
  title: string;
  topic: string;
  topiccolor: string;
  uid: string;
};
